### ISSUE TITLE
Repo does not have a license

### ISSUE THREAD

**Issue by jillr** [ansible-middleware/janus#11]
A license file is referenced in [galaxy.yml](https://github.com/ansible-middleware/janus/blob/main/galaxy.yml#L10) but there is no LICENSE file present, nor do any of the files in the collection contain license headers.  

An appropriate FLOSS license should be added to the root of the repo.

**Comment by rpelisse** [comment]
Closing as [PR14](https://github.com/ansible-middleware/janus/pull/14/files) added the missing license.
