### ISSUE TITLE
Repo needs usage documentation

### ISSUE THREAD

**Issue by jillr** [ansible-middleware/janus#13]
This repo would benefit from more documentation.  I'm trying to adapt the collection for the community.okd / redhat.openshift collection but it's not immediately obvious what the different vars are used for (and some values are hard-coded in the janus.yml playbook.)  I'm getting unexpected results but I'm not sure if it's user error or not.

For example, how do `upstream_name`, `upstream_namespace`, and `upstream_collection_name` relate to each other?  I can make an educated guess about `upstream_namespace` because it has a hard-coded value but I'm uncertain about the other 2.

Right now my resulting collection still has the upstream collection name (community.okd) in plugin EXAMPLES blocks, redirects in meta/runtime.yml, and my CONTRIBUTING.md file (as well as a number of test directories, such as /molecule/, but I don't expect janus to support that today).  I'm probably overlooking something, but I don't have confidence I'm doing the right thing in general.

Ideally IMO, janus would be a role that users can use rather than calling a playbook from another playbook and over-riding the vars that are in janus.yml.  That role would have a set of documented variables, with sensible role defaults where they can be made generic (such as the environment variable lookups for things like `PROJECT_UPSTREAM_NAME`, but no default of `upstream_namespace:  "middleware_automation"`).   That documentation should be adequate for a new user to configure a playbook for use with a new collection without having to dig into the underlying roles in [`middleware_automation/janus/roles/`.](https://github.com/ansible-middleware/janus/tree/main/roles)

Reference config:
```
(venv) jill@lab:~/collections/ansible_collections/middleware_automation/janus$ git diff
diff --git a/playbooks/janus.yml b/playbooks/janus.yml
index a2912ae..c37f985 100644
--- a/playbooks/janus.yml
+++ b/playbooks/janus.yml
@@ -5,14 +5,14 @@
   collections:
     - middleware_automation.janus
   vars:
-    upstream_name: "{{ lookup('env', 'PROJECT_UPSTREAM_NAME') }}"
-    downstream_name: "{{ lookup('env', 'PROJECT_NAME') }}"
-    upstream_collection_name: "{{ lookup('env', 'UPSTREAM_COLLECTION_NAME') | default(omit) }}"
-    project_git_url: "{{ lookup('env', 'GIT_REPOSITORY_URL') }}"
-    project_git_version: "{{ lookup('env', 'GIT_REPOSITORY_BRANCH') }}"
-    upstream_namespace:  "middleware_automation"
-    downstream_namespace: "redhat"
-    workdir: "{{ lookup('env', 'PWD') }}"
+#    upstream_name: "{{ lookup('env', 'PROJECT_UPSTREAM_NAME') }}"
+#    downstream_name: "{{ lookup('env', 'PROJECT_NAME') }}"
+#    upstream_collection_name: "{{ lookup('env', 'UPSTREAM_COLLECTION_NAME') | default(omit) }}"
+#    project_git_url: "{{ lookup('env', 'GIT_REPOSITORY_URL') }}"
+#    project_git_version: "{{ lookup('env', 'GIT_REPOSITORY_BRANCH') }}"
+#    upstream_namespace:  "middleware_automation"
+#    downstream_namespace: "redhat"
+#    workdir: "{{ lookup('env', 'PWD') }}"
     upstream_projects_dir: "{{ workdir }}/upstream"
     downstream_projects_dir: "{{ workdir }}/downstream"
     downstream_repository_host_env_varname: 'INTERNAL_GIT_REPOSITORY_URL'


(venv) jill@lab:~/collections/ansible_collections/middleware_automation/janus$ cat playbooks/openshift.yml 
---
- import_playbook: janus.yml
  vars:
    post_processors_replacements:
     - match: "community.okd"
       replace: "redhat.openshift"
     - match: "Ansible Galaxy"
       replace: "Automation Hub"
     - match: "Kubernetes"
       replace: "OpenShift"
     - match: " okd"
       replace: " openshift"
    upstream_name: "community.okd"
    downstream_name: "redhat.openshift"
    upstream_namespace: community
    downstream_namespace: redhat
    workdir: /var/tmp
    project_git_url: "git@github.com:openshift/community.okd"
    project_git_version: DNM_downstream_experiment
    downstream_repository_host_env_varname: localhost
```

**Comment by guidograzioli** [comment]
Absolutely, I'll start by creating the argument specs for the janus role, and using our tooling to generate a README so we have at least the variables docs.

**Comment by guidograzioli** [comment]
Should the changelog generation be useful, too?

**Comment by jillr** [comment]
If janus will use https://github.com/ansible-community/antsibull-changelog the docs can probably link to those docs, otherwise if there is a different changelog process then yes it would be helpful.

**Comment by guidograzioli** [comment]
yes, we have GH pipelines that take care of all that automatically, I'll add those bits too
( https://github.com/ansible-middleware/collection-docs-action )

**Comment by guidograzioli** [comment]
Infra for  ci, docs and changelog is merged, along with arg specs for the janus role; some more work is needed for proper default values, and "real" usage docs have to be written (#14 and #15); docs here:
http://ansiblemiddleware.com/janus/main/CHANGELOG.html and http://ansiblemiddleware.com/janus/main/roles/janus.html

**Comment by rpelisse** [comment]
@jillr I think we're good now :) but if you still have comments or feedback, please use the new repo!
