### ISSUE TITLE
Janus not in Galaxy

### ISSUE THREAD

**Issue by vkrizan** [ansible-middleware/janus#28]
##### SUMMARY

Hey Folks,

I'm unable to find this collection on Galaxy.
https://galaxy.ansible.com/middleware_automation/janus is not accessible.

Is it private?

##### ISSUE TYPE
 - Bug Report

##### STEPS TO REPRODUCE

```
$ ansible-galaxy collection install middleware_automation.janus
```

##### EXPECTED RESULTS

Installable from Galaxy.

##### ACTUAL RESULTS

```
ERROR! Failed to resolve the requested dependencies map. Could not satisfy the following requirements:
* middleware_automation.janus:* (direct request)
```

Thank you.

**Comment by guidograzioli** [comment]
Hello, it will be available soon in galaxy, but under a different name (janus clashes with some other tool, we will use ansible_raft), and we are currently working on it to clean the parts that are specific for our ansible namespace.

**Comment by vkrizan** [comment]
@guidograzioli Thanks! Let us know when it will be available.

**Comment by rpelisse** [comment]
@vkrizan We actually moved and rename Janus into [community.fqcn_migration](https://github.com/ansible-collections/community.fqcn_migration). This project can now be installed using Galaxy:

`$ ansible-galaxy collection install community.fqcn_migration`

If you still having problem, please open an issue on the new project.
